[package]
name = "sender"
version = "0.1.0"
authors = ["jamesmcnamara <jamesscottmcnamara@gmail.com>"]

[dependencies]
itertools = "0.4.1"
schedule_recv = "0.0.1"

[dependencies.packet]
path= "../packet"
